/*
 * Created on 2019-04-04 ( Date ISO 2019-04-04 - Time 17:54:15 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
 */

package com.acme.person;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.Properties;

import javax.sql.DataSource;

import org.junit.Assert;
import org.junit.Test;
import org.sparkyflow.jdbc.DataSourceProvider;



/**
 * JUnit tests for DataSourceProvider
 * 
 * @author Telosys 
 *
 */
public class DataSourceProviderTest {

	private void printProperty(Properties properties, String name) {
		String value = properties.getProperty(name);
		System.out.println(" . " + name + " = " + value );
		Assert.assertNotNull( value );
		Assert.assertFalse( "".equals(value.trim()));
	}

	@Test
	public void test1JdbcProperties() throws SQLException {
		System.out.println("--- test JDBC properties");
    	
		System.out.println("JDBC properties file name = '" + DataSourceProvider.getJdbcPrpertiesFileName() + "'");
		System.out.println(" properties file searched via classpath in : " );
		System.out.println(" 1 - 'src/test/resources' " );
		System.out.println(" 2 - 'src/main/resources' " );
		
		Properties properties = DataSourceProvider.loadJdbcPropertiesFromClassPath();

		System.out.println("JDBC properties values : " );
		printProperty(properties, "jdbc.url" );
		printProperty(properties, "jdbc.driverClassName" );
		printProperty(properties, "jdbc.username" );
		printProperty(properties, "jdbc.password" );		
	}
	
	@Test
	public void test2Connection() {
    	System.out.println("--- test Connection ");
    	Properties properties = DataSourceProvider.loadJdbcPropertiesFromClassPath();
    	
    	String driverClassName = properties.getProperty("jdbc.driverClassName");
    	String url  = properties.getProperty("jdbc.url").trim() ;
    	String user = properties.getProperty("jdbc.username").trim() ;
    	String password = properties.getProperty("jdbc.password").trim() ;
    	
    	System.out.println("Loading driver class...");
    	Class<?> driverClass = null ;
    	try {
    		driverClass = Class.forName(driverClassName);
		} catch (ClassNotFoundException e) {
			e.printStackTrace();
			throw new RuntimeException("Cannot load JDBC driver '" + driverClassName + "'");
		}
    	System.out.println("Driver class loaded : " + driverClass.getCanonicalName() );

    	System.out.println("Getting connection ...");
    	System.out.println("URL      : " + url );
    	System.out.println("user     : " + user );
    	System.out.println("password : " + password );
    	Connection con ;
    	try {
			con = DriverManager.getConnection(url, user, password);
		} catch (Exception e) {
			e.printStackTrace();
			throw new RuntimeException("Cannot get connection !");
		}
    	
    	try {
			con.getAutoCommit();
	    	System.out.println("auto-commit : " + con.getAutoCommit() );
			con.close();
		} catch (SQLException e) {
			e.printStackTrace();
			throw new RuntimeException("SQLException",e);
		}
	}
	
	@Test
	public void test3DataSource() throws SQLException {
    	System.out.println("--- test DataSourceProvider ");
    	
    	DataSource dataSource = DataSourceProvider.getDataSource();
    	System.out.println("DataSource ready. ");
    	
    	Connection c = dataSource.getConnection();
    	System.out.println("Connection ready. ");
    	
    	Assert.assertNotNull( c );
    	
    	c.close();
    	System.out.println("Connection closed. ");
	}
}
